TDevUIT/Bloai

- src/app/auth/layout.tsx
- src/app/layout.tsx
- src/components/AuthBackground.tsx
- src/lib/route.ts
- src/middleware.ts
- src/provider/app.sidebar.tsx
> fix(ui): adjust layout for AUTH ROUTE

- src/app/auth/layout.tsx
- src/section/Navbar.tsx
> fix: Route /auth/signin Not Displaying Without Reload

- public/robots.txt
- public/sitemap.xml
- src/components/Footer.tsx
- src/provider/app.sidebar.tsx
- src/server/auth/config.ts
> fix(ui): footer, change height sidebar

- next.config.js
- src/app/new-post/page.tsx
- src/server/api/routers/blog.ts
> fix: create new blog

- package-lock.json
- package.json
- src/app/auth/signin/page.tsx
> fix: auth google

- src/env.js
> fix: add env

- package-lock.json
- package.json
- src/app/auth/signin/page.tsx
- src/app/layout.tsx
- src/server/auth/config.ts
> chore: add Analytics, SpeedInsights

- prisma/schema.prisma
- src/env.js
> chore: add direct url

- package-lock.json
- package.json
- prisma/migrations/20250324140845_change_pro_fields/migration.sql
- prisma/schema.prisma
- src/app/blog/[slug]/page.tsx
- src/app/layout.tsx
- src/app/new-post/page.tsx
- src/components/BlogGrid.tsx
- src/provider/app.sidebar.tsx
- src/section/Navbar.tsx
- src/server/api/routers/blog.ts
- src/types/blog.ts
> feat: update ui and change schema

- prisma/schema.prisma
- src/app/blog/[slug]/page.tsx
- src/provider/app.sidebar.tsx
> fix: change database url, add button go to top

- next.config.js
- src/app/blog/[slug]/components/BlogPageContent.tsx
- src/app/blog/[slug]/page.tsx
- src/app/layout.tsx
- src/app/new-post/page.tsx
- src/app/not-found.tsx
- src/components/Dropzone.tsx
- src/hook/use-mobile.tsx
- src/section/Navbar.tsx
> feat: dynamic page, change seo, 404 page ui

- src/app/blog/[slug]/components/BlogPageContent.tsx
- src/app/layout.tsx
- src/app/new-post/page.tsx
- src/lib/action.ts
- src/lib/gemini.ts
- src/server/api/routers/blog.ts
> fix: unique tags create

- package-lock.json
- package.json
- src/app/layout.tsx
> chore: add GA

- src/app/(public)/contact/page.tsx
- src/app/blog/[slug]/components/BlogPageContent.tsx
- src/app/blog/[slug]/page.tsx
- src/app/page.tsx
- src/app/sitemap.ts
- src/components/BlogGrid.tsx
- src/components/Pagintion.tsx
- src/components/ui/bento-grid.tsx
- src/lib/route.ts
- src/server/api/routers/blog.ts
> feat: pagination, categories, suggest blog

- src/app/(public)/about/page.tsx
- src/app/blog/[slug]/page.tsx
> fix: route to 404 site, duplicate desc

- src/provider/app.sidebar.tsx
> hotfix: error build

- next.config.js
- src/app/blog/[slug]/components/BlogPageContent.tsx
- src/app/blog/[slug]/page.tsx
- src/app/layout.tsx
- src/app/sitemap.ts
- src/lib/route.ts
- src/middleware.ts
- src/styles/globals.css
> feat: outline, public route

- prisma/schema.prisma
- src/app/sitemap.ts
> fix: sitemap

- src/app/blog/[slug]/page.tsx
> fix: change props slug

- next.config.js
- src/app/blog/[slug]/components/BlogAuthorCard.tsx
- src/app/blog/[slug]/components/BlogContentRenderer.tsx
- src/app/blog/[slug]/components/BlogHeader.tsx
- src/app/blog/[slug]/components/BlogPageContent.tsx
- src/app/blog/[slug]/components/BlogPostClientWrapper.tsx
- src/app/blog/[slug]/components/BlogShareSidebar.tsx
- src/app/blog/[slug]/components/BlogTableOfContents.tsx
- src/app/blog/[slug]/components/SuggestedBlogCard.tsx
- src/app/new-post/components/DescriptionInputs.tsx
- src/app/new-post/components/NewPostContent.tsx
- src/app/new-post/components/SubmissionArea.tsx
- src/app/new-post/components/ThumbnailUploader.tsx
- src/components/logo.tsx
- src/server/api/routers/blog.ts
- src/styles/globals.css
> feat: update blog

- src/components/Navbar.tsx
- src/components/Pagintion.tsx
- src/components/Search.tsx
- src/components/blog/BlogGrid.tsx
- src/server/api/routers/blog.ts
> feat(#60): search 

- prisma/schema.prisma
> fix: push schema

- src/app/not-found.tsx
- src/lib/gemini.ts
- src/lib/uploadImageUrl.ts
> feat: change model, 404, valid iamge

- src/app/(public)/faqs/page.tsx
- src/app/(public)/privacy/page.tsx
- src/app/(public)/unsubscribe/page.tsx
- src/provider/app.sidebar.tsx
- src/server/api/routers/blog.ts
> feat: unsubscribe

- src/app/blog/[slug]/components/BlogComment.tsx
- src/app/blog/[slug]/components/BlogPostClientWrapper.tsx
- src/app/blog/[slug]/components/BlogSuggestedPosts.tsx
- src/app/blog/[slug]/components/SuggestedBlogCard.tsx
- src/app/blog/[slug]/page.tsx
- src/components/Navbar.tsx
- src/components/blog/BlogCard.tsx
- src/server/api/routers/blog.ts
- src/types/helper.type.ts
> feat: comment

- package-lock.json
- package.json
- src/components/Footer.tsx
- đổi icon twitter -> X
- thêm icon youtube+link
- thêm link face
> Update Footer component with X icon, facebook icon+link, youtub icon+link

- src/app/new-post/components/EditorWrapper.tsx
- src/components/blog/BlogFilterBar.tsx
- src/components/blog/BlogGrid.tsx
- src/lib/uploadImageUrl.ts
> feat: support image drag-and-drop in markdown editor for upload

- src/lib/action.ts
- src/lib/gemini.ts
> fix(#76): Image prompt rendering issue

- src/app/new-post/components/NewPostContent.tsx
- src/app/new-post/components/ThumbnailUploader.tsx
> fix(#79): prevent duplicate thumbnail uploads

- src/app/layout.tsx
- src/components/TestimonialSection.tsx
… results on Google Search
resolve #78 
> fix(#78): Missing author and itemReviewed fields causing invalid

- src/app/auth/signin/page.tsx
- src/app/auth/signup/page.tsx
- src/components/AuthBackground.tsx
> refactor: change ui auth page

- src/app/(public)/about/page.tsx
- src/app/(public)/contact/page.tsx
- src/app/(public)/landing/page.tsx
- src/app/(public)/tags/page.tsx
- src/components/Footer.tsx
- src/components/blog/BlogGrid.tsx
> fix: ahrefs issues

- src/app/new-post/components/ThumbnailUploader.tsx
- src/components/Dropzone.tsx
- src/components/Navbar.tsx
- src/components/TestimonialSection.tsx
- src/components/blog/BlogFilterBar.tsx
- src/components/blog/BlogGrid.tsx
> refactor: change small UI details

- src/app/blog/[slug]/components/BlogHeader.tsx
- src/components/LeaderBoard.tsx
- src/components/Navbar.tsx
- src/server/api/routers/blog.ts
> fix: avatar not displaying

- src/app/blog/[slug]/components/BlogComment.tsx
- src/app/new-post/components/NewPostContent.tsx
- src/components/LeaderBoard.tsx
- src/components/Navbar.tsx
- src/lib/uploadImageUrl.ts
> fix: avatar, ui

- src/components/Navbar.tsx
- src/components/Pagintion.tsx
- src/components/blog/BlogFilterBar.tsx
- src/components/blog/BlogGrid.tsx
- src/server/api/routers/blog.ts
> fix: filter tag

- src/components/Navbar.tsx
- src/components/blog/BlogFilterBar.tsx
> fix: navbar search

- src/app/(protected)/admin/layout.tsx
- src/app/(protected)/admin/page.tsx
- src/lib/route.ts
- src/middleware.ts
- src/provider/app.sidebar.tsx
> feat: admin page

- src/components/blog/BlogGrid.tsx
- src/middleware.ts
> feat(blog): implement URL-based pagination with page param

- package-lock.json
- package.json
- src/app/(protected)/admin/page.tsx
- src/components/ui/tabs.tsx
> fix: admin ui
